// <auto-generated />
using System;
using IntegracaoMilvusQlik.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegracaoMilvusQlik.Migrations
{
    [DbContext(typeof(IntegracaoMilvusQlikContext))]
    [Migration("20231016111335_initial1")]
    partial class initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegracaoMilvusQlik.Models.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .HasColumnType("text")
                        .HasColumnName("assunto");

                    b.Property<string>("CategoriaPrimaria")
                        .HasColumnType("text")
                        .HasColumnName("categoria_primaria");

                    b.Property<string>("CategoriaSecundaria")
                        .HasColumnType("text")
                        .HasColumnName("categoria_secundaria");

                    b.Property<string>("Cliente")
                        .HasColumnType("text")
                        .HasColumnName("cliente");

                    b.Property<string>("ClienteToken")
                        .HasColumnType("text")
                        .HasColumnName("cliente_token");

                    b.Property<int?>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<string>("Contato")
                        .HasColumnType("text")
                        .HasColumnName("contato");

                    b.Property<DateTime?>("DataAgendamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_agendamento");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_resposta");

                    b.Property<DateTime?>("DataSolucao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_solucao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("DescricaoAvaliacao")
                        .HasColumnType("text")
                        .HasColumnName("descricao_avaliacao");

                    b.Property<string>("EmailConferencia")
                        .HasColumnType("text")
                        .HasColumnName("email_conferencia");

                    b.Property<string>("EquipamentoRetirado")
                        .HasColumnType("text")
                        .HasColumnName("equipamento_retirado");

                    b.Property<string>("Impacto")
                        .HasColumnType("text")
                        .HasColumnName("impacto");

                    b.Property<string>("MaterialUtilizado")
                        .HasColumnType("text")
                        .HasColumnName("material_utilizado");

                    b.Property<string>("MesaTrabalho")
                        .HasColumnType("text")
                        .HasColumnName("mesa_trabalho");

                    b.Property<string>("Origem")
                        .HasColumnType("text")
                        .HasColumnName("origem");

                    b.Property<string>("Prioridade")
                        .HasColumnType("text")
                        .HasColumnName("prioridade");

                    b.Property<string>("ServicoRealizado")
                        .HasColumnType("text")
                        .HasColumnName("servico_realizado");

                    b.Property<string>("Setor")
                        .HasColumnType("text")
                        .HasColumnName("setor");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusSlaResposta")
                        .HasColumnType("text")
                        .HasColumnName("status_sla_resposta");

                    b.Property<string>("StatusSlaSolucao")
                        .HasColumnType("text")
                        .HasColumnName("status_sla_solucao");

                    b.Property<string>("Tecnico")
                        .HasColumnType("text")
                        .HasColumnName("tecnico");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoTicket")
                        .HasColumnType("text")
                        .HasColumnName("tipo_ticket");

                    b.Property<string>("TotalAvaliacao")
                        .HasColumnType("text")
                        .HasColumnName("total_avaliacao");

                    b.Property<string>("TotalHoras")
                        .HasColumnType("text")
                        .HasColumnName("total_horas");

                    b.Property<string>("Urgencia")
                        .HasColumnType("text")
                        .HasColumnName("urgencia");

                    b.HasKey("Id");

                    b.ToTable("lista");
                });
#pragma warning restore 612, 618
        }
    }
}
