// <auto-generated />
using System;
using IntegracaoMilvusQlik.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegracaoMilvusQlik.Migrations
{
    [DbContext(typeof(IntegracaoMilvusQlikContext))]
    [Migration("20231013135248_initial1")]
    partial class initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegracaoMilvusQlik.Models.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .HasColumnType("text");

                    b.Property<string>("CategoriaPrimaria")
                        .HasColumnType("text")
                        .HasColumnName("categoria_primaria");

                    b.Property<string>("CategoriaSecundaria")
                        .HasColumnType("text")
                        .HasColumnName("categoria_secundaria");

                    b.Property<string>("Cliente")
                        .HasColumnType("text");

                    b.Property<string>("ClienteToken")
                        .HasColumnType("text");

                    b.Property<int?>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Contato")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAgendamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoAvaliacao")
                        .HasColumnType("text");

                    b.Property<string>("DispositivoVinculado")
                        .HasColumnType("text");

                    b.Property<string>("EmailConferencia")
                        .HasColumnType("text");

                    b.Property<string>("EquipamentoRetirado")
                        .HasColumnType("text");

                    b.Property<string>("Impacto")
                        .HasColumnType("text");

                    b.Property<string>("MaterialUtilizado")
                        .HasColumnType("text");

                    b.Property<string>("MesaTrabalho")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .HasColumnType("text");

                    b.Property<string>("ServicoRealizado")
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StatusSlaResposta")
                        .HasColumnType("text");

                    b.Property<string>("StatusSlaSolucao")
                        .HasColumnType("text");

                    b.Property<string>("Tecnico")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("TipoTicket")
                        .HasColumnType("text");

                    b.Property<string>("TotalAvaliacao")
                        .HasColumnType("text");

                    b.Property<string>("TotalHoras")
                        .HasColumnType("text");

                    b.Property<string>("Urgencia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("lista");
                });
#pragma warning restore 612, 618
        }
    }
}
